import NewDate from "../../utils/NewDate";
export default {
  date: NewDate(),
  name: "",
  dob: "",
  cough: false,
  fever: false,
  throat: false,
  headache: false,
  // nose: false,
  // sneeze: false,
  // smellTaste: false,
  // breath: false,
  // aches: false,
  // fatigue: false,
  // lesions: false,
  // diarrhea: false,
  // day14Travel: "",
  // closeContact: "",
  // clusterHub: "",
  // covidRisk: "",
  // tested: "",
  // dateOfSwab: "",
  // other: "",
  // verifiedBy: "",
  // updateBy: "",
  breath: false,
  nosimp: false,
  shortbreath: false,
  nosimp2: false,
  testedpositive: false,
  waitingresults: false,
  hadcontact: false,
  travelled: false,
  requirements: false,
};
